export const LOCAL_USER_INFO = 'LOCAL_USER_INFO'
export const LOGINSTATE = 'LOGINSTATE'
export const COUNT = 'COUNT'
export const COM_SHOW_SIDE_BAR = 'COM_SHOW_SIDE_BAR'
export const SET_USERTIME = 'SET_USERTIME'
export const RECORD_HOME_LIST = 'RECORD_HOME_LIST'
export const ADD_ZAN_NUM = 'ADD_ZAN_NUM'